### ISSUE TITLE
Prefixを変更可能に

### ISSUE THREAD

**Issue by AI-Avalon** [AntiquePendulum/ApexRandomBot#4]
現状のPrefix"!"だと、かぶってしまうことが多い為、セルフホストする際に変更可能にしていただきたいです。

**Comment by Anteccq** [comment]
@AI-Avalon 
対応しますので数日お待ち下さい 🙇

**Comment by AI-Avalon** [comment]
ありがとうございます
お時間のある時で大丈夫ですのでゆっくりやってください！

**Comment by Anteccq** [comment]
@AI-Avalon 
長らく報告できず申し訳ありません。

本 Bot のリニューアルバージョンを公開いたしましたのでよければこちらをご利用下さい。
https://github.com/Anteccq/ApexRandomGachaBot

Prefix の変更を構成ファイルから行えるよう改善しています。

**Comment by AI-Avalon** [comment]
わざわざありがとうございます！
使用させていただきます！！
