### ISSUE TITLE
Legend と Weponの文字を出す際に画像付きで出せるとありがたいです

### ISSUE THREAD

**Issue by AI-Avalon** [AntiquePendulum/ApexRandomBot#5]
初心者などとたまに遊ぶときにぱっと浮かばない時があるのでできれば画像も一緒に出力してもらえるとありがたいです。
画像を当てはめる場所さえ作っていただければ私が代わりに埋めることもできるのでご一考いただけると嬉しいです

**Comment by Anteccq** [comment]
@AI-Avalon 
ありがとうございます。
画像周りは権利周りに特に気を使わなければならないのを気にしていて、今の所標準で搭載する考えはないですね...

**Comment by AI-Avalon** [comment]
確かにそこまでの考えは回っていませんでした。
安易な画像引用はトラブルの元ですからね…
ご返答ありがとうございます
